deploy-to-vercel:
  stage: deploy
  image: node:13.10.1-alpine3.10

  variables:
    PREVIEW_URL=https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app

  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: $PREVIEW_URL

  script:
    - npm i -g vercel 
    - vercel --prod